### ISSUE TITLE
[ADD] ToDoList by AbstractSpoon

### ISSUE THREAD

**Issue by abstractspoon** [0PandaDEV/awesome-windows#1]
### Application Name

ToDoList

### Application URL

https://www.abstractspoon.com

### Category

Productivity

### Description

![image](https://github.com/user-attachments/assets/ef351f08-1891-41cf-9187-5b0694d8ab03)

### Application Attributes

- [X] Free
- [X] Open Source
- [ ] Paid
- [ ] Freemium (free with paid features)

### Repository URL

https://github.com/abstractspoon/ToDoList_Dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abstractspoon** [comment]
https://github.com/abstractspoon

**Comment by 0PandaDEV** [comment]
why did you ping yourself?

**Comment by 0PandaDEV** [comment]
btw a pr would be easier i will probably make a guidlines on how to make a pr but thanks for the suggestion.
